"""baseline schema

Revision ID: 1160bf4cd340
Revises: 
Create Date: 2026-09-01 20:23:46.696520
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '1160bf4cd340'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('kl_grade', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('max_angle', sa.Integer(), nullable=False),
    sa.Column('knee_side', sa.String(length=8), nullable=False),
    sa.Column('surgery_type', sa.String(length=16), nullable=False),
    sa.Column('weeks_post_op', sa.Integer(), nullable=True),
    sa.Column('rehab_phase', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('demo_mode', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index('ix_prescriptions_patient_created', ['patient_id', 'created_at'], unique=False)

    op.create_table('exercise_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('client_session_id', sa.String(length=64), nullable=False),
    sa.Column('prescription_id', sa.String(length=32), nullable=True),
    sa.Column('exercise_name', sa.String(length=120), nullable=False),
    sa.Column('tracked_joint', sa.String(length=8), nullable=False),
    sa.Column('knee_side', sa.String(length=8), nullable=False),
    sa.Column('angle_limit', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('hold_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_set_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sets_completed', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('view_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'client_session_id', name='uq_session_patient_client')
    )
    with op.batch_alter_table('exercise_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_patient_started', ['patient_id', 'started_at'], unique=False)

    op.create_table('exercise_sets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('reps_completed', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('peak_flexion_deg', sa.Float(), nullable=False),
    sa.Column('breach_count', sa.Integer(), nullable=False),
    sa.Column('breach_seconds', sa.Float(), nullable=False),
    sa.Column('hold_seconds_achieved', sa.Float(), nullable=True),
    sa.Column('mean_visibility', sa.Float(), nullable=True),
    sa.Column('suspended_seconds', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exercise_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'set_index', name='uq_set_session_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_sets')
    with op.batch_alter_table('exercise_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_patient_started')

    op.drop_table('exercise_sessions')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_prescriptions_patient_created')

    op.drop_table('prescriptions')
    op.drop_table('patients')
    # ### end Alembic commands ###
