"""add pain and exertion ratings

Revision ID: 3ae6c7860066
Revises: 1160bf4cd340
Create Date: 2026-09-01 20:24:05.420992
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '3ae6c7860066'
down_revision: Union[str, None] = '1160bf4cd340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pain_before', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pain_after', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rpe', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_sessions', schema=None) as batch_op:
        batch_op.drop_column('rpe')
        batch_op.drop_column('pain_after')
        batch_op.drop_column('pain_before')

    # ### end Alembic commands ###
