"""store the operation date

Revision ID: a4fb606dfbc9
Revises: 3ae6c7860066
Create Date: 2026-09-02 21:10:18.692126
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'a4fb606dfbc9'
down_revision: Union[str, None] = '3ae6c7860066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surgery_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('surgery_type', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('surgery_type')
        batch_op.drop_column('surgery_date')

    # ### end Alembic commands ###
