"""clinicians and care links

Revision ID: a61cd5decb49
Revises: 36ec3895dc13
Create Date: 2026-09-02 21:55:50.289317
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'a61cd5decb49'
down_revision: Union[str, None] = '36ec3895dc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinicians',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('registration', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('care_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('clinician_id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=True),
    sa.Column('invite_code_hash', sa.String(length=64), nullable=False),
    sa.Column('invite_hint', sa.String(length=16), nullable=False),
    sa.Column('patient_label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinicians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code_hash')
    )
    with op.batch_alter_table('care_links', schema=None) as batch_op:
        batch_op.create_index('ix_care_links_clinician', ['clinician_id', 'accepted_at'], unique=False)
        batch_op.create_index('ix_care_links_patient', ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('care_links', schema=None) as batch_op:
        batch_op.drop_index('ix_care_links_patient')
        batch_op.drop_index('ix_care_links_clinician')

    op.drop_table('care_links')
    op.drop_table('clinicians')
    # ### end Alembic commands ###
