"""clinical review and audit

Revision ID: cc19af88dbbd
Revises: a61cd5decb49
Create Date: 2026-09-02 22:19:50.182262
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'cc19af88dbbd'
down_revision: Union[str, None] = 'a61cd5decb49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription_audit',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('prescription_id', sa.String(length=32), nullable=False),
    sa.Column('exercise_name', sa.String(length=120), nullable=True),
    sa.Column('field', sa.String(length=24), nullable=False),
    sa.Column('previous_value', sa.String(length=64), nullable=True),
    sa.Column('new_value', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('clinician_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinicians.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescription_audit', schema=None) as batch_op:
        batch_op.create_index('ix_audit_prescription', ['prescription_id', 'created_at'], unique=False)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        # server_default, not just a Python-side default: this column is NOT NULL
        # and every prescription already in the table predates it. Without a
        # default the upgrade fails outright, and with a Python one it would
        # only apply to rows written afterwards. Existing analyses are drafts —
        # nobody has reviewed them, because until now nobody could.
        batch_op.add_column(sa.Column('status', sa.String(length=24), nullable=False,
                                      server_default='draft'))
        batch_op.add_column(sa.Column('reviewed_by_clinician_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('review_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('approved_payload', sa.Text(), nullable=True))
        # Named, not None: SQLite cannot alter a table in place, so batch mode
        # rebuilds it — and it cannot rebuild a constraint it has no name for.
        batch_op.create_foreign_key(
            'fk_prescriptions_reviewed_by_clinician', 'clinicians',
            ['reviewed_by_clinician_id'], ['id'], ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prescriptions_reviewed_by_clinician', type_='foreignkey')
        batch_op.drop_column('approved_payload')
        batch_op.drop_column('review_note')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_clinician_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('prescription_audit', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_prescription')

    op.drop_table('prescription_audit')
    # ### end Alembic commands ###
